### ISSUE TITLE
error: 'pixels' was not declared in this scope

### ISSUE THREAD

**Issue by makeSmartio** [mike-rankin/ESP32_Stock_Ticker#1]
Am I missing a library? When I compile, I get:
`In function 'void setup()':
Stock_Ticker_Demo:61:3: error: 'pixels' was not declared in this scope
   pixels.begin();`

**Comment by mike-rankin** [comment]
I believe you need to install the Adafruit_NeoPixel library.

**Comment by makeSmartio** [comment]
Sure enough, my mistake. I accidentally removed this line #include <Adafruit_NeoPixel.h>
